spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bankdb
    username: postgres
    password: 1
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        hbm2ddl:
          import_files: init.sql
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current_session_context_class=org:
          springframework:
            orm:
              hibernate5:
                SpringSessionContext:
