spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bankdb
    username: postgres
    password: 1
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        current_session_context_class=org:
          springframework:
            orm:
              hibernate5:
                SpringSessionContext:
